### ISSUE TITLE
组合龙漏计四归一

### ISSUE THREAD

**Issue by Quinoxaline** [summerinsects/ChineseOfficialMahjongHelper#10]
组合龙和四归一复合时 若刻子为副露明刻
(牌例[999p]147m258s369pPP) 四归一漏计
若刻子为暗刻则无漏计bug

**Comment by Quinoxaline** [comment]
> 组合龙和四归一复合时 若刻子为副露明刻
(牌例[999p]147m258s369pPP) 四归一漏计 若刻子为暗刻则无漏计bug

**Comment by summerinsects** [comment]
v1.5.1.8修了
