### ISSUE TITLE
计分模式下缺少明暗杠

### ISSUE THREAD

**Issue by xuanyan0x7c7** [summerinsects/ChineseOfficialMahjongHelper#3]

**Comment by summerinsects** [comment]
由于「明暗杠」不算太正统的番种，所以暂时没有放在计分选择里，以后再考虑增加

**Comment by summerinsects** [comment]
https://github.com/summerinsects/ChineseOfficialMahjongHelper/commit/43909c985f939196f2701ddadfa7f8bd63beb845
