### ISSUE TITLE
缺少258将

### ISSUE THREAD

**Issue by zhoujianshi** [summerinsects/ChineseOfficialMahjongHelper#6]
这个repo真的太棒了！不过我发现缺少了258将的判断，可以增加吗？

**Comment by summerinsects** [comment]
258将并非国标麻将标准番种，所以未做处理

如果需要的话，可以自行修改代码，增加如下几处：
- 在fan_calculator.h中：
1. 在`enum fan_t { };` 合适的位置增加，比如叫 `PAIR_258`
2. 在`const char *fan_name[] = {};` 相应的位置增加 `__UTF8("258将")`
3. 在`const uint16_t fan_value_table[FAN_TABLE_SIZE]` 相应的位置增加 258将的番值，比如为1番

二、fan_calculator.cpp中：
1. 找到函数`static void adjust_by_pair_tile(tile_t pair_tile, intptr_t chow_cnt, fan_table_t &fan_table)`，在最后增加如下代码：
```c++
// 258将的判断
if (is_numbered_suit_quick(pair_tile) && tile_get_rank(pair_tile) % 3 == 2) {
    fan_table[PAIR_258] = 1;
}
```

2. 找到函数`static void adjust_fan_table(fan_table_t &fan_table)`，找到如下三个if分支：
1) `if (fan_table[PURE_TERMINAL_CHOWS])`
2) `if (fan_table[THREE_SUITED_TERMINAL_CHOWS])`
3) `if (fan_table[ALL_FIVE])`
在三个if里面增加：`fan_table[PAIR_258] = 0;`
因为以上三个番种是必然258将的，根据国标麻将的一般计番原则，需要不计它
