### ISSUE TITLE
算番库中组合龙算番bug

### ISSUE THREAD

**Issue by castor-v-pollux** [summerinsects/ChineseOfficialMahjongHelper#9]
国标计番规则：组合龙普通型和牌中，可加计平和。如果听牌既可以解释为组合龙的部分，也可以解释为边张、嵌张、单吊，可加计边张、嵌张、单吊。

目前算番库实现中，考虑了加计平和，但是没有考虑听牌同时构成组合龙以及边坎吊的情况，以下是复现案例：
unit_test.cpp:
	test_points("13347s12369m258p3m", WIN_FLAG_DISCARD, wind_t::EAST, wind_t::EAST); //应为组合龙门清平和边张，漏计边张
	test_points("13347s23469m258p3m", WIN_FLAG_DISCARD, wind_t::EAST, wind_t::EAST); //应为组合龙门清平和坎张，漏计坎张
	test_points("1147s123369m258p1s", WIN_FLAG_DISCARD, wind_t::EAST, wind_t::EAST); //应为组合龙门清平和单钓将，漏计单钓将
以及可能需要考虑更复杂的情况，比如听牌同时构成组合龙以及边坎吊中的至少两个，如147s2333469m258p3m为组合龙门清平和四归一+(坎张单吊二选一)，通常习惯选坎张。

希望能尽快修复~

**Comment by summerinsects** [comment]
您好，对于听牌在组合龙9张牌范围内的牌型，国际麻将联盟(MIL)自己都不统一，其线下比赛支持计，其认可的线上平台又不计，对此本app选择不计
如果您需要加计，可打开文件fan_calculator.cpp，找到函数calculate_knitted_straight_fan，自行修改相应逻辑

**Comment by castor-v-pollux** [comment]
明白了，请教一下具体的修改方案是将1835行的if条件改为true吗？我不太确定是否理解了目前的代码逻辑

**Comment by summerinsects** [comment]
应该是可以的，不过我没做过测试，你多找几个测试用例试试

**Comment by castor-v-pollux** [comment]
OK，谢谢

**Comment by summerinsects** [comment]
@castor-v-pollux 你好，简单去掉那个if条件是不行的，会把一副露的组合龙判定为单钓。现在的最新代码已经实现的两种模式，可用宏控制
